from __future__ import annotations

from enum import StrEnum


class LotStatus(StrEnum):
    RECEBIDO = "RECEBIDO"
    PROCESSANDO = "PROCESSANDO"
    CONCLUIDO = "CONCLUIDO"
    CONCLUIDO_COM_ERROS = "CONCLUIDO_COM_ERROS"


class LineStatus(StrEnum):
    ERRO_VALIDACAO = "ERRO_VALIDACAO"
    NA_FILA = "NA_FILA"
    EM_PROCESSAMENTO = "EM_PROCESSAMENTO"
    SUCESSO_TOTAL = "SUCESSO_TOTAL"
    SUCESSO_PARCIAL = "SUCESSO_PARCIAL"
    ERRO_PROCESSAMENTO = "ERRO_PROCESSAMENTO"


class DownloadStatus(StrEnum):
    BAIXADO = "BAIXADO"
    NAO_ENCONTRADO = "NAO_ENCONTRADO"
    NAO_SOLICITADO = "NAO_SOLICITADO"
    FALHA = "FALHA"


class ErrorCode(StrEnum):
    ERRO_VALIDACAO = "ERRO_VALIDACAO"
    ERRO_LOGIN = "ERRO_LOGIN"
    ERRO_SENHA_INVALIDA = "ERRO_SENHA_INVALIDA"
    ERRO_USUARIO_INVALIDO = "ERRO_USUARIO_INVALIDO"
    ERRO_PORTAL_INDISPONIVEL = "ERRO_PORTAL_INDISPONIVEL"
    ERRO_TIMEOUT = "ERRO_TIMEOUT"
    ERRO_CONTA_NAO_ENCONTRADA = "ERRO_CONTA_NAO_ENCONTRADA"
    ERRO_FATURA_NAO_ENCONTRADA = "ERRO_FATURA_NAO_ENCONTRADA"
    ERRO_PDF_NAO_DISPONIVEL = "ERRO_PDF_NAO_DISPONIVEL"
    ERRO_AE_NAO_DISPONIVEL = "ERRO_AE_NAO_DISPONIVEL"
    ERRO_LAYOUT_ALTERADO = "ERRO_LAYOUT_ALTERADO"
    ERRO_CAPTCHA = "ERRO_CAPTCHA"
    ERRO_SEM_PERMISSAO = "ERRO_SEM_PERMISSAO"
    ERRO_REFERENCIA_INVALIDA = "ERRO_REFERENCIA_INVALIDA"
    ERRO_DOWNLOAD = "ERRO_DOWNLOAD"
    ERRO_DESCONHECIDO = "ERRO_DESCONHECIDO"


DEFAULT_AE_FORMATS = ("AE", "TXT", "ZIP", "CSV")
TERMINAL_LINE_STATUSES = {
    LineStatus.ERRO_VALIDACAO,
    LineStatus.SUCESSO_TOTAL,
    LineStatus.SUCESSO_PARCIAL,
    LineStatus.ERRO_PROCESSAMENTO,
}
